-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('NEW_JOB_AVAILABLE', 'BID_RECEIVED', 'BID_ACCEPTED', 'BID_DECLINED', 'JOB_SCHEDULED', 'JOB_IN_PROGRESS', 'JOB_COMPLETED', 'JOB_CANCELLED', 'JOB_REMINDER', 'SCHEDULE_CHANGE', 'SUBSCRIPTION_CREATED', 'SUBSCRIPTION_RENEWED', 'SUBSCRIPTION_CANCELLED', 'NEW_PROVIDER_SIGNUP', 'PAYOUT_SENT', 'GENERAL') NOT NULL;
